name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: projectuser
          POSTGRES_PASSWORD: projectpass
          POSTGRES_DB: projectdb
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U projectuser -d projectdb"
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Alembic migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python -m alembic upgrade head
      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pytest -q

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install and build frontend
        run: |
          npm ci
          npm run build